# -*- coding: utf-8 -*-
"""diabetes_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEXtmFHJnDYpjLBK7QFExSjklJUFTPBc

Importing the dependencies
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data collection and analysis
PIMA Diabetes Dataset
"""

diabetes_dataset=pd.read_excel('/content/diabetes.csv.xlsx')

diabetes_dataset.head()

diabetes_dataset.tail()

diabetes_dataset.shape

#getting the statistcal measures ofthe data
diabetes_dataset.describe()

diabetes_dataset['Outcome'].value_counts()

"""0-->Non-Diabetic
1-->diabetec
"""

diabetes_dataset.groupby('Outcome').mean()

#seperating the data and labels
x=diabetes_dataset.drop(columns='Outcome',axis=1)
y=diabetes_dataset['Outcome']

print(x)

print(y)

"""Data standardization:it is a preprocessing technique used to keep all elements in the colums will be of same value and in then the mean will be 0 and standard_deviation will be 1"""

scaler = StandardScaler()

scaler.fit(x)

standardized_data = scaler.transform(x)

print(standardized_data)

diabetes_dataset.describe()

x=standardized_data
y=diabetes_dataset['Outcome']

print(x)

print(y)

"""Train_test_split"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

print(x.shape,x_train.shape,x_test.shape)

classifier=svm.SVC(kernel='linear')

classifier.fit(x_train,y_train)

x_train_prediction=classifier.predict(x_train)
trainiing_data_accuracy=accuracy_score(x_train_prediction,y_train)

print("accuracy score of the training data :",trainiing_data_accuracy)

x_test_prediction =classifier.predict(x_test)
testing_data_accuracy=accuracy_score(x_test_prediction,y_test)

print("accuracy of testing data is :",testing_data_accuracy)

input_data=(1,85,66,29,0,26.6,0.351,31)
#lets convert  it into numpy array
input_data_array=np.asarray(input_data)
#lets reshape the array so the machine can understand we are predicting for one instace
input_data_reshaped=input_data_array.reshape(1,-1)
#lets standardize the data
std_data=scaler.transform(input_data_reshaped)
prediction=classifier.predict(std_data)
print(prediction)
if (prediction[0]==0):
  print("the person is not diabetic")
else:
  print("the person is diabetic")

